# Generated by Django 4.0 on 2022-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_authors_book_category_book_publishedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
