# Generated by Django 4.0 on 2022-02-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_authors_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
