# Generated by Django 4.0 on 2022-02-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0008_rename_authors_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shortDescription',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
